### ISSUE TITLE
模型下载地址失效了

### ISSUE THREAD

**Issue by lonycc** [PyUnit/pyunit-ner#2]
求补档

**Comment by jtyoui** [comment]
@lonycc https://github.com/PyUnit/pyunit-ner/releases/download/v1.0/model.tar.gz

**Comment by jtyoui** [comment]
@lonycc 请使用`docker`部署，`docker pull jtyoui/pyunit-ner:latest`,使用文档查看：https://github.com/PyUnit/pyunit-ner#%E6%8A%BD%E5%8F%96%E5%AE%9E%E4%BD%93%E6%8E%A5%E5%8F%A3%E6%96%87%E6%A1%A3
