### ISSUE TITLE
 cannot import name 'ernie_st'

### ISSUE THREAD

**Issue by szm863** [PyUnit/pyunit-ner#4]
pip install but dont't  cannot import name 'ernie_st'

**Comment by jtyoui** [comment]
> pip install but dont't cannot import name 'ernie_st'

Preloaded [model](https://github.com/PyUnit/pyunit-ner/releases/download/v1.0/model.tar.gz) file in your local env, see [MODEL_PATH=xxx](https://github.com/PyUnit/pyunit-ner/blob/6f3acd41c3b673be4c08409b7194a4a87437e39b/pyunit_ner/ner.py#L35).

README.ME Docs are some problem, use reference [main.py](https://github.com/PyUnit/pyunit-ner/blob/6f3acd41c3b673be4c08409b7194a4a87437e39b/main.py#L41) code file.
